#!/bin/bash
mkdir qwerty #2
cd qwerty #3
mkdir qwerty2 qwerty3 qwerty4 #4
cd qwerty2 #5
touch 1.txt 2.txt 3.txt 4.json 5.json #6
mkdir qwerty5 qwerty6 qwerty7 #7
ls -la #8
mv 1.txt 4.json qwerty7 #13





